### ISSUE TITLE
Numbering typo?

### ISSUE THREAD

**Issue by randyhart** [18F/bpa-identity-management#1]
In the RFQ - I wasn't clear on where 7(b)(ii) and 7(b)(iii) were in the RFQ.  Might need to be renumbered?

>Phase 2: Technical Compliance Check. Review of Written Technical Quotations to ensure that offerors meet technical requirements as outlined in Section 7(b)(ii) and Section 7(b)(iii) of the RFQ, and the PWS

**Comment by markmohler** [comment]
This looks like a format/copy issue between the eBuy and Github. "Similar Experience" should be (iii), but looks to have restarted at (i). It correctly shows as (iii) in the eBuy RFQ PDF version

**Comment by randyhart** [comment]
cool - this should be an easy fix.  thanks @markmohler.
