### ISSUE TITLE
Relation to Connect.gov

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-identity-management#10]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation

Patrick McConnell, Agile BPA Manager, SemanticBits

## Section of RFQ documents

PWS 1.0 BACKGROUND

## Question/Comment

Will the government please describe the relationship between this effort and Connect.gov?

**Comment by jposi** [comment]
The Government has described the relationship between past work and this effort in this forum: https://18f.gsa.gov/2016/05/10/building-a-modern-shared-authentication-platform/
