### ISSUE TITLE
Technical Features

### ISSUE THREAD

**Issue by teralogicsllc** [18F/bpa-identity-management#12]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Eric Vogel, Cubic | TeraLogics, Agile BPA Manager 

## Section of RFQ documents
PWS 3.0 Scope

## Question/Comment
Would the 18F staff please elaborate on the required “technical features,” referenced in PWS 3.0 Scope, due by Nov 2016? This will help us determine the staff best fit for this opportunity.

**Comment by jposi** [comment]
As stated in the PWS, SAML and OpenID connect will be needed, and pointed you to the repositories that exist. As reminder, this will be developed using Ruby, and agency code bases is likely to include Java, depending on the agencies we partner with.
