### ISSUE TITLE
Key Personnel Requirements

### ISSUE THREAD

**Issue by teralogicsllc** [18F/bpa-identity-management#13]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Eric Vogel, Cubic | TeraLogics, Agile BPA Manager

## Section of RFQ documents
PWS, 5.5.2 Key Personnel / QASP 1.2.2 Results Focus

## Question/Comment
Will the 18F staff please consider reducing or removing the current key personnel requirements? This would allow “the contractor flexibility to continuously improve and innovate over the course of the contract as long as the critical outcomes expected are being achieved and/or the desired performance levels are being met;” a desire stated in the QASP 1.2.2 Results Focus section.  The flexibility of personnel assignment improves our ability to provide the best service and expertise over the life of the award.

**Comment by jposi** [comment]
Please see Issue #8.
