### ISSUE TITLE
COTS or Custom

### ISSUE THREAD

**Issue by bothanus** [18F/bpa-identity-management#14]
# Question/Comment on PWS for Identity Management Shared Authentication Platform Support

## Name and affiliation
Nico Botha - Booz Allen Hamilton

## Section of RFQ documents
PWS 3.0 - Scope

## Question/Comment
Will the solution integrate with a COTS (or Open Source) Identity Management product, or is the Identity Manager going to be custom built by this team?

**Comment by jposi** [comment]
As a shared service, we expect to integrate with both COTS and Open Source tools. The role of this scrum team will be to work on integrating existing agency products with the 18F Identity Platform.
