### ISSUE TITLE
Design of Login.gov

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#15]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - Applied Information Sciences - Agile BPA Manager

## Section of RFQ documents
N/A

## Question/Comment
Could you provide any diagrams or design documents dictating at a high level what would be the desired end state/to be architecture and describe the type of support needed by the vendors for this task order?

**Comment by jposi** [comment]
The most detailed information we can share at this point is in the Github repositories we've provided as well as in our blog posts. https://18f.gsa.gov/2016/05/10/building-a-modern-shared-authentication-platform/
