### ISSUE TITLE
Scale Requirements

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#16]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - Applied Information Sciences - Agile BPA Manager

## Section of RFQ documents
Section 4 PWS  

## Question/Comment
Does 18F expect the vendor to provide past performance to the Scale described  in Section 4 as well as provide the key personnel that either supported that past performance or similar experience?

**Comment by jposi** [comment]
18F expects that past performance would be at the scale requested but we do not require that the key personnel that will be provided are necessarily on those examples. Please continue to follow the directions in the RFQ provided.
