### ISSUE TITLE
Agency Partners

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-identity-management#17]
# Question/Comment on Identity Management RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0 Requirements
“Contractor will work with 18F Identity Management team to improve the 18F identity management product to meet the requirements of the agency partners.”  

## Question/Comment
Will the team be working directly on the 18F identity product or integrating between the identify product, citizens and other government sites?  Will the team be working directly with agency partners or only with 18F?

**Comment by jposi** [comment]
Depending on the project status at the time of award, the contractor team is expected to work with 18F and any revelant stakeholders to further develop this project. 18F expects that  vendors will have contact with agency partners for technical work, as appropriate.
