### ISSUE TITLE
IDM Technical Overview

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#18]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - Applied Information Sciences - Agile BPA Manager

## Section of RFQ documents
N/A

## Question/Comment
Could you provide any more detailed diagrams for the login.gov solution as it is today, than the system document located in the docs\security folder within the github repo?

**Comment by jposi** [comment]
No, we cannot provide any more diagrams at this time. Please refer to Issue #15 as well.
