### ISSUE TITLE
IDM Engine

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#19]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - Applied Information Sciences - Agile BPA Manager

## Section of RFQ documents
N/A 

## Question/Comment
What is the core piece or engine for the login.gov solution?

**Comment by jposi** [comment]
Right now, the prototype is a SAML based Identity Provider written in Ruby on Rails.

**Comment by jposi** [comment]
edited that initial comment to remove the word "prototype", which was an incorrect description.
