### ISSUE TITLE
Connect.gov Reuse

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#20]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - AIS - AGile BPA Manager

## Section of RFQ documents
N/A

## Question/Comment
Are there any aspects of Connect.gov being utilized and if so please identify which pieces?

**Comment by jposi** [comment]
We are not currently directly using components of connect.gov in this project, but there is clearly a technological overlap.
