### ISSUE TITLE
Authentication Services

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-identity-management#21]
# Question/Comment on Identity Management RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents
Attachment 1 PWS, Section 4.0 Requirements
“Contractor will work with agency partners and 18F Identity Management team to build integration (using Security Assertion Markup Language (SAML) or other appropriate technology) between agency web properties and 18F identity management products.” 

## Question/Comment
Will “build integration” include building authentication services including directory services that support LDAP/RADIUS or social media authentication including Facebook or Google Authentication?

**Comment by jposi** [comment]
Currently, the integrations involve SAML. We do not plan to support LDAP/RADIUS. That may change as the product develops.
