### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#22]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - AIS - Agile BPA Manager

## Section of RFQ documents
Section 5.5.1

## Question/Comment
Most of the existing Solution is written Ruby, in the PWS you mention NodeJs or Django, how will you see these two frameworks being utilized during the engagement?

**Comment by jposi** [comment]
The core identity project is currently written in Ruby. Because we anticipate the work of this team will involve other agencies and their existing codebases, we wanted to make sure that the vendor is prepared to work with multiple different languages.
