### ISSUE TITLE
Cloud providers

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-identity-management#24]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
Jason McNutt - AIS - Agile BPA Manager

## Section of RFQ documents
N/A

## Question/Comment
Which Cloud Vendor is being utilized for the IaaS piece?

**Comment by jposi** [comment]
This will be determined in the coming months. We don't expect that to impact the work of this vendor scrum team.
