### ISSUE TITLE
Ruby Open Source

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#26]
# Question/Comment on Identity Mgt

## Name and affiliation
David @ DSoft

## Question/Comment
•	Looking at the Github site we can see that most of the existing code is written in Ruby.  Are there other Open Source projects are being used or planned to be used in the technical solution?  Have any of the OSS projects been scaled in a production environment to the required metric for login.gov?

**Comment by jposi** [comment]
We are relying on a number of open source projects that are at various stages of development.
