### ISSUE TITLE
Coding Test

### ISSUE THREAD

**Issue by brianfunk** [18F/bpa-identity-management#28]
# Question/Comment on Identity Management RFQ

## Name and affiliation
Brian Funk - NCI, Inc - Agile BPA Manager

## Section of RFQ documents

Attachment 4 states: “an online written coding test will consist of a small online project whose development will not last more than 3 hours.”  

RFQ states: “The code test will be focused on the Offeror’s experience and skill with DevOps, infrastructure, and continuous deployment methods.”

## Question/Comment
Can you please clarify if this code test will consist of software development/coding or DevOps/infrastructure/continuous deployment or both?  How many people do you anticipate participating in this code test?

**Comment by jposi** [comment]
That doesn't read well, thanks for catching that. The test will require software development and infrastructure skills, and will require no more than 2 people. We will release more information to the vendors who reach the Oral Interview stage of this process.
