### ISSUE TITLE
UK's Identity Mgt Solution

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#29]
# Question/Comment on Identity Mgt

## Name and affiliation
David @ DSoft

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

## Question/Comment
•	Is the UK identity solution related to the login.gov work and is any of the UK solutions code being leveraged?

**Comment by jposi** [comment]
We are in dialogue with the UK, but because their work is not Open Source we are unable to reuse their code at this point in time.
