### ISSUE TITLE
General Identity Management System Strategy

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#30]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation
David @ DSoft 

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

## Question/Comment
•	Why is 18F custom building an identity engine when there are several proven commercial engines that scale to the required metrics for login.gov?  Would the government consider using a commercial identity engine and customizing the solution as needed as originally planned?

**Comment by jposi** [comment]
We have considered many different technical approaches for this solution based on the needs of the agencies across the government.  The initial approach leverages a really good mix of commercial solutions and government built solutions.  We will continually iterate on our approach as the government needs and the commercial/open source solutions evolve.
