### ISSUE TITLE
18F’s identity management product

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#32]
# Question/Comment on Identity Mgt

## Name and affiliation
David @ DSoft

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

## Question/Comment
Given that a major aspect of this task order is integrating 18F’s identity management product, is there a technical overview and detailed technical information available that would provide a better understanding of the level of effort that would be involved?

**Comment by jposi** [comment]
Please see issue #15.
