### ISSUE TITLE
Commercial identity management 

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#33]
# Question/Comment on Identity Mgt

## Name and affiliation
David @ DSoft

## Section of RFQ documents
{please be specific about the section of the RFQ documents you have a question or comment about, if applicable}  

## Question/Comment
•	Does the design of login.gov follow a “provider”-styled pattern where the actual identity provider is configurable?  For example, with several commercial identity management offering innovative identity and authentication capabilities, will the design allow a commercial identity management to be chosen when configuring applications that use login.gov?

**Comment by jposi** [comment]
This question is not relevant to the work required.
