### ISSUE TITLE
100’s and 1000s of transactions per second

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#34]
# Question/Comment on Identity Mgt

## Name and affiliation
David @ DSoft

## Section of RFQ documents
Section 4 of the PWS

## Question/Comment
•	In section 4 of the PWS, when describing the task requirements that the contractor must successfully perform, it mentions building integration between web apps and the 18F identity management product, providing feedback 18F, and working with 18F management.  Later in the desired skills and knowledge section it mentions experience with highly scalable systems of 100s or 1000s of Transactions per Second.  Connecting those two things, is the question of experience and knowledge related to scaling websites to 100’s and 1000s of transactions per second?

**Comment by jposi** [comment]
Experience and knowledge is, as the PWS says, related to integrating external tools with 18F's codebase and an external to GSA agency's code. In addition, experience and knowledge related to scaling websites to 100s and 1000s of transactions per second is requested, per the request in Similar Experience.
