### ISSUE TITLE
Remote development team

### ISSUE THREAD

**Issue by dsoft-dh** [18F/bpa-identity-management#35]
# Question/Comment on Identity Mgt RFQ

## Name and affiliation
David @ DSoft

## Section of RFQ documents
Place of Performance (6.3) 

## Question/Comment
Please clarify “Staff may also be distributed or work at their homes, per agreement with the Government Product Owner”.  Can a remote development team (outside the DC area) support this TO?

**Comment by jposi** [comment]
Please refer to Issue #5.
