### ISSUE TITLE
Place of Performance

### ISSUE THREAD

**Issue by sarahruggless** [18F/bpa-identity-management#5]
Question on Identity Management RFQ

PWS Section 6.3 Place and Hours of Performance

Can you please clarify if some or all or none of the team for this project need to be onsite? The PWS states the GSA headquarters and alternate sites but then also states that staff may be distributed or work from home. Does 18F have a preference for where the team is located (remote vs onsite)?

**Comment by jposi** [comment]
18F expects that the contractor will be onsite at GSA Headquarters at 1800 F Street NW. They will be required to travel to agencies at times. Per the PWS they may be able to work remotely, with the approval of the Product Owner.
