### ISSUE TITLE
Recent and Similar Technical Scope

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-identity-management#7]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation

Patrick McConnell, Agile BPA Manager for SemanticBits

## Section of RFQ documents

RFQ 7.B.iii.iii. Recent and Similar Technical Scope

PWS 4.0 REQUIREMENTS

## Question/Comment

Please confirm the Similar Experience requirement:

> iii. Recent and Similar Technical Scope: Recent and similar technical scope is past experience with building usable, responsive, consumer facing web site serving at least a million users, built within the past three (3) years.

It does not seem to relate to the work required for this task order identified in 4.0 REQUIREMENTS:

> Contractor will work with agency partners and 18F Identity Management team to build integration (using Security Assertion Markup Language (SAML) or other appropriate technology) between agency web properties and 18F identity management product.

**Comment by jposi** [comment]
The Government finds this to be consistent. If you do not agree, please provide similar experience requirements that you feel would make them more consistent.
