### ISSUE TITLE
Key Personnel

### ISSUE THREAD

**Issue by patrickmcconnell** [18F/bpa-identity-management#8]
# Question/Comment on FedRamp Dashboard RFQ

## Name and affiliation

Patrick McConnell, Agile BPA Manager, SemanticBits

## Section of RFQ documents

PWS 5.5.2 Key Personnel

## Question/Comment

Please confirm that you are looking for 4-5 highly experienced individuals that are not currently on any project (and thus available) to be key personnel on task.  If so, please consider reducing the key personnel requirements.

**Comment by jposi** [comment]
We will keep this as it is. We will review this for future procurements.
