### ISSUE TITLE
Similar Experience

### ISSUE THREAD

**Issue by sarahruggless** [18F/bpa-identity-management#9]
# Question/Comment on Identity Management RFQ

## Name and affiliation
Sarah Ruggless - VP of Public Sector, Flexion Inc.

## Section of RFQ documents
RFQ, Section 7. b. iii. Similar Experience

## Question/Comment
The Similar Experience section asks for one example of a scrum team that has worked in close collaboration with an agency. Will the government accept a commercial client project as an example or must it be a federal government agency project?

**Comment by jposi** [comment]
The government will accept a commercial client project as an example. Currently the RFQ doesn't require federal projects, so we will not be making changes to the RFQ.
